### ISSUE TITLE
nginx fails with "413 Request Entity Too Large" if I try and validate my shrinkwrap file using grunt-nsp-shrinkwrap

### ISSUE THREAD

**Issue by pdehaan** [nodesecurity/grunt-nsp-shrinkwrap#8]
I'm trying to validate a 1.1MB npm-shrinkwrap.json file using grunt-nsp-shrinkwrap, and the server seems to be blowing up.

Repo in question is https://github.com/mozilla/fxa-content-server

### Steps to reproduce:
1. `git clone git@github.com:mozilla/fxa-content-server.git`
2. `rm npm-shrinkwrap.json`
3. `npm i`
4. `npm shrinkwrap --dev`
5. `grunt validate-shrinkwrap`
6. weep.

```
fxa-content-server.CRITICAL: TypeError: Object <html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
 has no method 'forEach'
```

---

```sh
$ ls -lah npm-sh*
-rw-r--r--  1 pdehaan  staff   1.1M Mar 23 10:48 npm-shrinkwrap.json
```

```sh
$ grunt validate-shrinkwrap

Running "validate-shrinkwrap" task
/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/npm-shrinkwrap.json
fxa-content-server.CRITICAL: TypeError: Object <html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
 has no method 'forEach'
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
 has no method 'forEach'
    at Request._callback (/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/grunt-nsp-shrinkwrap/tasks/shrinkwrap.js:46:26)
    at Request.self.callback (/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/request/request.js:123:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/request/request.js:1047:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/request/request.js:998:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
Fatal error: Object <html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
 has no method 'forEach'


Execution Time (2015-03-23 17:50:37 UTC)
loading tasks        3.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 74%
validate-shrinkwrap  1.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 26%
Total 5s
```

But it seems to work fine if I just use `nsp` directly from the CLI:
```
$ nsp shrinkwrap

Name          Installed       Patched       Vulnerable Dependency
qs              0.6.6          >= 1.x       fxa-content-server > bower > bower-registry-client > request
qs              0.6.6          >= 1.x       fxa-content-server > bower > bower-registry-client > request
qs              0.6.6          >= 1.x       fxa-content-server > bower > request
qs              0.6.6          >= 1.x       fxa-content-server > bower > request
qs              0.6.6          >= 1.x       fxa-content-server > coveralls > request
qs              0.6.6          >= 1.x       fxa-content-server > coveralls > request
serve-index     1.2.1         >=1.6.3       fxa-content-server > express > connect
serve-static    1.6.4    ~1.6.5 || >=1.7.2  fxa-content-server > express > connect
qs              0.5.6          >= 1.x       fxa-content-server > grunt-contrib-watch > tiny-lr-fork
qs              0.5.6          >= 1.x       fxa-content-server > grunt-contrib-watch > tiny-lr-fork
marked          0.3.2         >=0.3.3       fxa-content-server > grunt-marked
```

**Comment by pdehaan** [comment]
![](http://whattheflicka.com/wp-content/uploads/2014/08/What-the-fuck-GIFS.gif)

**Comment by evilpacket** [comment]
Y U GOTTA HAVE BIG SHRINKWRAP? lol

We'll take a look and figure out what's going on with it.

**Comment by bear** [comment]
the default size nginx has for payloads/uploads is 1 meg -- I can increase this limit but would need to know what a good max is?

**Comment by pdehaan** [comment]
Y U GOTTA RESTRICT PAYLOAD SIZE?

Just set the max payload size to `Number.POSITIVE_INFINITY`. #infinitepayload #problemsolved

**Comment by evilpacket** [comment]
@pdehaan haha who would ever need more than 640k anyway? (we'll update the limit)

**Comment by pdehaan** [comment]
Thanks guys! #xoxo

**Comment by bear** [comment]
limit updated in nginx to 5meg

**Comment by pdehaan** [comment]
@bear: I'm still seeing the "413 Request Entity Too Large" message. :confused: 

Not sure if you need to unplug the server for 15 seconds and plug it back in.

**Comment by pdehaan** [comment]
nginx config aside, I filed #9, _"Validate that the server responded with a valid JSON response before calling forEach"_, which is basically where the code is failing and where you may want to add an additional check before calling the `forEach()`. Feel free to mock and close.

**Comment by bear** [comment]
also bumped the hapijs payload maxBytes value to 5meg

**Comment by pdehaan** [comment]
@bear: still seeing the error when using the Grunt task.
Let me know if there is something else I should be testing.
I cant quite figure out why the CLI version and grunt version aren't matching up.

As close as I can get is that [grunt-nsp-shrinkwrap](https://github.com/nodesecurity/grunt-nsp-shrinkwrap/blob/9302febecdc297bee28547e6c64b928afcde44c3/tasks/shrinkwrap.js#L21) is using `fs.createReadStream()` and piping to **request**, whereas the **nsp-api** module seems to push the JSON blob all at once.

Only other oddity was that we're seemingly setting the **request** module's `json` parameter to a JSON object in [nsp-api](https://github.com/nodesecurity/nsp-api/blob/41f8cff89d8de70e7ff674f6f7ac202e9fff49ee/src/index.js#L26) but in the [grunt-nsp-shrinkwrap](https://github.com/nodesecurity/grunt-nsp-shrinkwrap/blob/9302febecdc297bee28547e6c64b928afcde44c3/tasks/shrinkwrap.js#L28) it is a Boolean.

**Comment by pdehaan** [comment]
Actually, it looks like setting the `json` parameter in **request** to an object is valid:

> **`body`** - entity body for PATCH, POST and PUT requests. Must be a `Buffer` or `String`, unless `json` is `true`. If `json` is `true`, then `body` must be a JSON-serializable object.

> **`json`** - sets `body` but to JSON representation of value and adds `Content-type: application/json` header. Additionally, parses the response body as JSON.

I just done learned something new!

**Comment by bear** [comment]
@pdehaan please try it again, my push of a new nginx config did not deploy correctly. manually verified now.

**Comment by pdehaan** [comment]
A different error appears:

```
$ grunt validate-shrinkwrap

Running "validate-shrinkwrap" task
/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/npm-shrinkwrap.json
fxa-content-server.CRITICAL: TypeError: Object <!DOCTYPE html><html><head><meta charset="utf-8"><title>Node Security Project | </title><meta name="viewport" content="width=device-width,initial-scale=1.0"><link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/2.3.1/css/bootstrap.min.css"><link rel="stylesheet" href="/css/app.css"><link rel="alternate" type="application/rss+xml" title="Node Security Advisories" href="/rss.xml"><link href="https://fonts.googleapis.com/css?family=Lato:400,900" rel="stylesheet" type="text/css"><link rel="icon" href="/img/nodesecurity.png"><script type="text/javascript" src="//code.jquery.com/jquery-2.0.0.min.js"></script><script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/2.3.1/js/bootstrap.min.js"></script></head><body><header class="container row"><div role="title" class="span6"><a href="/"><img src="/img/nodesecurity.png" class="title-image"></a><h1 class="title">Node Security Project</h1><span class="subtitle">We need a tagline contributor™</span></div><div class="span4 search pull-right"><div class="social pull-right"><a href="https://twitter.com/nodesecurity"><img src="/img/webicon-twitter.png"></a><a href="https://github.com/nodesecurity"><img src="/img/webicon-github.png"></a></div></div></header><br><div class="menu navbar container"><div class="container"><div role="navigation" class="nav-collapse collapse"><ul class="nav"><li><a href="/advisories">View Advisories</a></li><li><a href="mailto:report@nodesecurity.io?subject=NodeSecurity Vuln Report">Report Vulnerability</a></li><li><a href="/resources">Resources</a></li><li><a href="http://blog.nodesecurity.io">Blog</a></li><li></li></ul></div></div></div><div role="main" class="content-container"><div class="container"><div class="row-fluid"><div class="hero-unit advisory-detail"><h2>something went wrong</h2></div></div></div></div><script src="/js/gs.js"></script><footer><p>Organized by <a href="http://liftsecurity.io">^Lift Security</a> Sponsored by <a href="http://andyet.com">&amp;yet</a> Powered by The Node.js Community<a href=""></a></p></footer><script type="text/javascript">var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-103128-11']);
_gaq.push(['_trackPageview']);

(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();</script></body></html> has no method 'forEach'
_gaq.push(['_setAccount', 'UA-103128-11']);
_gaq.push(['_trackPageview']);

(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();</script></body></html> has no method 'forEach'
    at Request._callback (/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/grunt-nsp-shrinkwrap/tasks/shrinkwrap.js:46:26)
    at Request.self.callback (/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/request/request.js:123:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/request/request.js:1047:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/request/request.js:998:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
Fatal error: Object <!DOCTYPE html><html><head><meta charset="utf-8"><title>Node Security Project | </title><meta name="viewport" content="width=device-width,initial-scale=1.0"><link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/2.3.1/css/bootstrap.min.css"><link rel="stylesheet" href="/css/app.css"><link rel="alternate" type="application/rss+xml" title="Node Security Advisories" href="/rss.xml"><link href="https://fonts.googleapis.com/css?family=Lato:400,900" rel="stylesheet" type="text/css"><link rel="icon" href="/img/nodesecurity.png"><script type="text/javascript" src="//code.jquery.com/jquery-2.0.0.min.js"></script><script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/2.3.1/js/bootstrap.min.js"></script></head><body><header class="container row"><div role="title" class="span6"><a href="/"><img src="/img/nodesecurity.png" class="title-image"></a><h1 class="title">Node Security Project</h1><span class="subtitle">We need a tagline contributor™</span></div><div class="span4 search pull-right"><div class="social pull-right"><a href="https://twitter.com/nodesecurity"><img src="/img/webicon-twitter.png"></a><a href="https://github.com/nodesecurity"><img src="/img/webicon-github.png"></a></div></div></header><br><div class="menu navbar container"><div class="container"><div role="navigation" class="nav-collapse collapse"><ul class="nav"><li><a href="/advisories">View Advisories</a></li><li><a href="mailto:report@nodesecurity.io?subject=NodeSecurity Vuln Report">Report Vulnerability</a></li><li><a href="/resources">Resources</a></li><li><a href="http://blog.nodesecurity.io">Blog</a></li><li></li></ul></div></div></div><div role="main" class="content-container"><div class="container"><div class="row-fluid"><div class="hero-unit advisory-detail"><h2>something went wrong</h2></div></div></div></div><script src="/js/gs.js"></script><footer><p>Organized by <a href="http://liftsecurity.io">^Lift Security</a> Sponsored by <a href="http://andyet.com">&amp;yet</a> Powered by The Node.js Community<a href=""></a></p></footer><script type="text/javascript">var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-103128-11']);
_gaq.push(['_trackPageview']);

(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();</script></body></html> has no method 'forEach'
```

**Comment by pdehaan** [comment]
Not sure if it helps anybody, but the full npm-shrinkwrap.json can be found in this not-so-secret Gist: https://gist.github.com/pdehaan/97aec44cf90849563d72

**Comment by evilpacket** [comment]
@pdehaan thx.

I just pulled that repo, did npm i and then grunt validate-shrinkwrap and I got this as a result 

```
Running "validate-shrinkwrap" task
/Users/adam_baldwin/Documents/projects/fxa-content-server/npm-shrinkwrap.json
>> Name          Installed       Patched       Vulnerable Dependency
>> qs              0.6.6          >= 1.x       fxa-content-server > bower > bower-registry-client > request
>> qs              0.6.6          >= 1.x       fxa-content-server > bower > bower-registry-client > request
>> qs              0.6.6          >= 1.x       fxa-content-server > bower > request
>> qs              0.6.6          >= 1.x       fxa-content-server > bower > request
>> serve-index     1.2.1         >=1.6.3       fxa-content-server > express > connect
>> serve-static    1.6.4    ~1.6.5 || >=1.7.2  fxa-content-server > express > connect
>> marked          0.3.2         >=0.3.3       fxa-content-server > grunt-marked
Warning: known vulnerable modules found Use --force to continue.

Aborted due to warnings.


Execution Time (2015-03-23 19:55:37 UTC)
loading tasks        3.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 42%
validate-shrinkwrap  4.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 58%
Total 7.6s

```

**Comment by pdehaan** [comment]
@evilpacket You may need to delete the existing npm-shrinkwrap.json file (don't think it has devDependencies) and then run `npm install`, then regenerate `npm-shrinkwrap --dev`.

The current [npm-shrinkwrap.json](https://github.com/mozilla/fxa-content-server/blob/master/npm-shrinkwrap.json) file in GitHub is 7,620 lines, whereas the one WITH devDependencies (the one I posted in the [Gist](https://gist.github.com/pdehaan/97aec44cf90849563d72)) is roughly 21,325 lines.

**Comment by evilpacket** [comment]
13:08:24-adam_baldwin~/Documents/projects/fxa-content-server (master)$ wc -l npm-shrinkwrap.json
   21330 npm-shrinkwrap.json

```
13:07:59-adam_baldwin~/Documents/projects/fxa-content-server (master)$ grunt validate-shrinkwrap
Running "validate-shrinkwrap" task
/Users/adam_baldwin/Documents/projects/fxa-content-server/npm-shrinkwrap.json
No vulnerable modules found

Done, without errors.
```

Does not mean this is the right result it's just what I get after doing what you said.

**Comment by pdehaan** [comment]
Ah! OK, we're gettin somewhere!

```sh
$ grunt validate-shrinkwrap

Running "validate-shrinkwrap" task
/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/npm-shrinkwrap.json
No vulnerable modules found

Done, without errors.


Execution Time (2015-03-23 20:10:38 UTC)
loading tasks        3.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 76%
validate-shrinkwrap  1.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 24%
Total 5.1s
```

So I'm not getting an error anymore, but the fact it says "No vulnerable modules found" is mildly pants-crapping.

**Comment by pdehaan** [comment]
PS: You guys are awesome!

**Comment by bear** [comment]
@pdehaan is this ok to close now?

**Comment by evilpacket** [comment]
@pdehaan yes that does concern me as well. I have to take a break and get some work done, but will continue the adventure this evening....

We are planning a lot of API changes in the future here too so maybe this will start to jump start that..

**Comment by evilpacket** [comment]
@bear nope still an issue

**Comment by bear** [comment]
ah - it's more than the 413 error -gotcha

/me re-lurks

**Comment by pdehaan** [comment]
Current status:

## without devDependencies (`$ npm shrinkwrap`):

```
$ rm npm-shrinkwrap.json && npm shrinkwrap

npm WARN shrinkwrap Excluding devDependency: awsbox
npm WARN shrinkwrap Excluding devDependency: coveralls
npm WARN shrinkwrap Excluding devDependency: execSync
npm WARN shrinkwrap Excluding devDependency: firefox-profile
npm WARN shrinkwrap Excluding devDependency: grunt-bump
npm WARN shrinkwrap Excluding devDependency: grunt-contrib-csslint
npm WARN shrinkwrap Excluding devDependency: grunt-contrib-imagemin
npm WARN shrinkwrap Excluding devDependency: grunt-contrib-jshint
npm WARN shrinkwrap Excluding devDependency: grunt-contrib-watch
npm WARN shrinkwrap Excluding devDependency: grunt-conventional-changelog
npm WARN shrinkwrap Excluding devDependency: grunt-copyright
npm WARN shrinkwrap Excluding devDependency: grunt-jscs
npm WARN shrinkwrap Excluding devDependency: grunt-jsonlint
npm WARN shrinkwrap Excluding devDependency: grunt-nsp-shrinkwrap
npm WARN shrinkwrap Excluding devDependency: grunt-todo
npm WARN shrinkwrap Excluding devDependency: intern-geezer
npm WARN shrinkwrap Excluding devDependency: jshint
npm WARN shrinkwrap Excluding devDependency: jshint-stylish
npm WARN shrinkwrap Excluding devDependency: request
npm WARN shrinkwrap Excluding devDependency: xmlhttprequest
wrote npm-shrinkwrap.json

$ grunt validate-shrinkwrap
Running "validate-shrinkwrap" task
/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/npm-shrinkwrap.json
>> Name          Installed       Patched       Vulnerable Dependency
>> qs              0.6.6          >= 1.x       fxa-content-server > bower > bower-registry-client > request
>> qs              0.6.6          >= 1.x       fxa-content-server > bower > bower-registry-client > request
>> qs              0.6.6          >= 1.x       fxa-content-server > bower > request
>> qs              0.6.6          >= 1.x       fxa-content-server > bower > request
>> serve-index     1.2.1         >=1.6.3       fxa-content-server > express > connect
>> serve-static    1.6.4    ~1.6.5 || >=1.7.2  fxa-content-server > express > connect
>> marked          0.3.2         >=0.3.3       fxa-content-server > grunt-marked
Warning: known vulnerable modules found Use --force to continue.

Aborted due to warnings.


Execution Time (2015-03-23 20:13:03 UTC)
loading tasks         3.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 85%
validate-shrinkwrap  560ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇ 15%
Total 3.7s
```

## WITH devDependencies (`$ npm shrinkwrap --dev`):
```
$ rm npm-shrinkwrap.json && npm shrinkwrap --dev
wrote npm-shrinkwrap.json

$ grunt validate-shrinkwrap
Running "validate-shrinkwrap" task
/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/npm-shrinkwrap.json
No vulnerable modules found

Done, without errors.


Execution Time (2015-03-23 20:13:24 UTC)
loading tasks          3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 72%
validate-shrinkwrap  1.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 28%
Total 4.2s

**Comment by pdehaan** [comment]
@bear: I'll leave it to you guys to decide if you want to close this. Technically it looks like the nginx+hapi payload issue is fixed and working, so the bug is technically fixed.

Now the current problem is that if the request somehow fails, we just assume everything was fine and tell the user everything passed :poop:.

I'm fine if you want to close this out and just track the issue in #9 instead.

**Comment by evilpacket** [comment]
@pdehaan I'd suggest checking out grunt-requiresafe now as it's much more accurate than nsp was and WAY more performant. We can actually check the package.json (without shrinkwrap) for this project in under 16 seconds, it does not finish in under an hour with nsp. 

Note the new plugin isn't drop in compatible, but it's pretty straight forward. Would love feedback.

**Comment by pdehaan** [comment]
@evilpacket: Awesome, thanks!
I was actually looking at {grunt|gulp}-requiresafe yesterday (as well as shrinkydink) and will try and look more this week.

Not sure if you want to publish a eslint-config-requiresafe ESLint config and then make sure all your github.com/requiresafe/* repos use the same linting styles. I think only a few repos had an .eslintrc file.
